// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA661whOhr5da5wMVagagNCjkq1Y64QwWM',
    appId: '1:829576828752:web:ed1e95df977c4f666a3e55',
    messagingSenderId: '829576828752',
    projectId: 'justap-8acd8',
    authDomain: 'justap-8acd8.firebaseapp.com',
    storageBucket: 'justap-8acd8.appspot.com',
    measurementId: 'G-ML0NHY2BPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfy2XTFKt1Mu8MtkzDQHUQ39WLeVJQkQ',
    appId: '1:829576828752:android:01d843b1ef6df3326a3e55',
    messagingSenderId: '829576828752',
    projectId: 'justap-8acd8',
    storageBucket: 'justap-8acd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83mDO0fs5eXhKElEOexrqOC0_SqG5VM0',
    appId: '1:829576828752:ios:8199580f4a6a6b5d6a3e55',
    messagingSenderId: '829576828752',
    projectId: 'justap-8acd8',
    storageBucket: 'justap-8acd8.appspot.com',
    iosClientId:
        '829576828752-60ph4dpnohq7q40sohg6dcl7h9ct49a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.justap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC83mDO0fs5eXhKElEOexrqOC0_SqG5VM0',
    appId: '1:829576828752:ios:8199580f4a6a6b5d6a3e55',
    messagingSenderId: '829576828752',
    projectId: 'justap-8acd8',
    storageBucket: 'justap-8acd8.appspot.com',
    iosClientId:
        '829576828752-60ph4dpnohq7q40sohg6dcl7h9ct49a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.justap',
  );
}
